import { Field, InputType } from '@nestjs/graphql';
import { IsNotEmpty } from 'class-validator';

@InputType()
export class TriggerMFALoginInput {
  @Field({
    description: `A unique, real-world identifier (e.g., email, phone number) used for authentication or user identification`,
  })
  @IsNotEmpty()
  naturalKey!: string;
}

@InputType()
export class FinishMFALoginInput extends TriggerMFALoginInput {
  @Field({
    description: `A time-sensitive authentication code for MFA, generated by an authenticator device or received via SMS/email`,
  })
  token!: string;
}
