image: node:18-alpine

cache:
  - key: yarn-workspace
    paths:
      - node_modules/
      - .yarn

stages:
  - build
  - test
  - comment
  - release

build:
  stage: build
  script:
    - yarn --immutable
    - yarn build
  cache:
    paths:
      - node_modules/
      - .yarn

changeset-mr-comment:
  stage: comment
  needs: ["build"]
  only: ["merge_requests"]
  script:
    - yarn --immutable
    - yarn changesets-gitlab comment

test:
  stage: test
  needs: ["build"]
  script:
    - yarn --immutable
    - yarn test
    - yarn lint
  cache:
    paths:
      - node_modules/
      - .yarn

release:
  only: ["main"]
  script:
    - yarn --immutable
    - yarn changesets-gitlab
