image: node:20-alpine

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

cache:
  - key: yarn-workspace
    paths:
      - node_modules/
      - .yarn

stages:
  - build
#  tmp disabled due to:
# Could not find a working container runtime strategy
# const pgContainer = await new PostgreSqlContainer()
#  - test
  - comme'nt
  - release

build-lib:
  stage: build
  only: ["merge_requests", "main"]
  script:
    - yarn --immutable
    - yarn build  --filter='./libs/*'
  artifacts:
    paths:
      - libs/crud/dist
      - libs/nestjs-utils/dist

build-samples:
  stage: build
  only: ["merge_requests", "main"]
  allow_failure: true
  script:
    - yarn --immutable
    - yarn build  --filter='./samples/*'
  artifacts:
    paths:
      - libs/crud/dist
      - libs/nestjs-utils/dist

# changeset-mr-comment:
#   stage: comment
#   only: ["merge_requests"]
#   script:
#     - yarn --immutable
#     - yarn changesets-gitlab comment

test-lib:
  stage: test
  only: ["merge_requests", "main"]
  script:
    - yarn --immutable
    - yarn turbo run test --filter='./libs/*'
    - yarn turbo run lint --filter='./libs/*'
  artifacts:
    paths:
      - libs/**/coverage*/
  cache:
    paths:
      - node_modules/
      - .yarn

test-samples:
  stage: test
  only: ["merge_requests", "main"]
  allow_failure: true
  script:
    - yarn --immutable
    - yarn turbo run test --filter='./samples/*'
    - yarn turbo run lint --filter='./samples/*'
  cache:
    paths:
      - node_modules/
      - .yarn

release:
  stage: release
  only: ["main"]
  script:
    - apk add --no-cache git
    - yarn --immutable
    - yarn postinstall
    - yarn changesets-gitlab
  variables:
    INPUT_PUBLISH: yarn release
