/* tslint:disable prettier/prettier */
/* eslint-disable prettier/prettier */
/* prettier-ignore */
// automatically generated by catladder. Do not modify!
export {}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ENV_SHORT: string
      ROOT_URL: string
      PORT: string
      AIRTABLE_API_KEY: string
      GRAPHQL_ENDPOINT: string
      ASSET_SERVER_ENDPOINT: string
    }
  }
}
