/* tslint:disable prettier/prettier */
/* eslint-disable prettier/prettier */
/* prettier-ignore */
// automatically generated by catladder. Do not modify!
export {}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ENV_SHORT: string
      ROOT_URL: string
      PORT: string
      JWT_SECRET: string
      GCLOUD_CREDENTIALS: string
      CONSTANT_OTP: string
      SENTRY_DSN: string
      GCLOUD_BUCKET_PUBLIC: string
      DB_PASSWORD: string
      JWT_EXPIRATION: string
      FRONTEND_URL: string
      NO_COLOR: string
      LOG_GQL_QUERY: string
      REGISTRATION_ENABLED: string
      I18N_LANGUAGE: string
      DATABASE_URL: string
      ENV: string
      LOG_LEVEL: string
    }
  }
}
