
/* tslint:disable prettier/prettier */
/* eslint-disable prettier/prettier */
/* prettier-ignore */
// automatically generated by ts-i18n. Do not modify!


export type ResourcesWithoutNamespace = "address.canton"
"common.accept" |
"common.actions" |
"common.active" |
"common.addFilter" |
"common.areYouSureQuestion" |
"common.assets" |
"common.cancel" |
"common.closeAction" |
"common.continue" |
"common.createdAt" |
"common.date" |
"common.deactivate" |
"common.delete" |
"common.description" |
"common.download" |
"common.edit" |
"common.error" |
"common.export" |
"common.fullTextSearch" |
"common.import" |
"common.images" |
"common.loadingData" |
"common.mainImage" |
"common.mandatoryField" |
"common.new" |
"common.noData" |
"common.price" |
"common.reject" |
"common.respond" |
"common.saveAction" |
"common.showLess" |
"common.showMore" |
"common.status" |
"common.title" |
"common.updateAt" |
"common.phase" |
"common.deleteRecord"
"resources.Autocomplete.fields.key" |
"resources.Autocomplete.fields.value" |
"validation.constraints.minLength"

 export type ResourcesWithNamespace = "common:address.canton" |
"common:address.city" |
"common:address.country" |
"common:address.firstName" |
"common:address.lastName" |
"common:address.postalCode" |
"common:address.postalCodeDescription" |
"common:address.streetAndNumber" |
"common:address.submitNewAddress" |
"common:address.yourAddress" |
"common:auth.loginForm.email.error" |
"common:auth.loginForm.email.label" |
"common:auth.loginForm.otpCode.error" |
"common:auth.loginForm.otpCode.label" |
"common:auth.loginForm.popupHeader" |
"common:auth.loginForm.submitGetOptCode" |
"common:auth.loginForm.submitLogin" |
"common:building-component.breadcrump.buildingComponents" |
"common:common.accept" |
"common:common.actions" |
"common:common.active" |
"common:common.addFilter" |
"common:common.areYouSureQuestion" |
"common:common.assets" |
"common:common.cancel" |
"common:common.closeAction" |
"common:common.continue" |
"common:common.createdAt" |
"common:common.date" |
"common:common.deactivate" |
"common:common.delete" |
"common:common.description" |
"common:common.download" |
"common:common.edit" |
"common:common.error" |
"common:common.export" |
"common:common.fullTextSearch" |
"common:common.import" |
"common:common.images" |
"common:common.loadingData" |
"common:common.mainImage" |
"common:common.mandatoryField" |
"common:common.new" |
"common:common.noData" |
"common:common.price" |
"common:common.reject" |
"common:common.respond" |
"common:common.saveAction" |
"common:common.showLess" |
"common:common.showMore" |
"common:common.status" |
"common:common.title" |
"common:common.updateAt" |
"common:common.phase" |
"common:common.deleteRecord"
"common:form.graphqlModal.title.create" |
"common:form.graphqlModal.title.edit" |
"common:resources.Autocomplete.fields.key" |
"common:resources.Autocomplete.fields.value" |
"common:validation.constraints.minLength"

 export type Resources = ResourcesWithNamespace | ResourcesWithoutNamespace;
